apiVersion: apps/v1
kind: Deployment
metadata:
  name: idocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idocs
  template:
    metadata:
      labels:
        app: idocs
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        ports:
        - containerPort: 80

