apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.werf.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $.Values.werf.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.werf.name }}
    spec:
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        ports:
        - containerPort: 80

