name: Production Deployment
on:
  push:
    branches: [main]

jobs:
  call-deployment:
    uses: iconicompany/iconicactions/.github/workflows/deployment.yml@v0.3.0
    secrets: inherit
    with:
      env: production
      setenv: env.DOMAIN=iconicompany.ru
