name: Production Deployment
on:
  push:
    branches: [main]

jobs:
  call-deployment:
    uses: iconicompany/werfactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      env: production
      setenv: env.DOMAIN=iconicompany.ru
